apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-app-hpa
  namespace: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-app-deployment          # Phải khớp với tên Deployment ở trên
  minReplicas: 2             # Số Pod tối thiểu (luôn duy trì ít nhất 2)
  maxReplicas: 6            # Số Pod tối đa khi tải cực cao
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Scale khi CPU trung bình của dàn Pod > 120m (60% của 200m)

